# fly.toml app configuration file generated for fuckyour-email on 2024-10-04T15:41:32-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fuckyour-email'
primary_region = 'sea'
console_command = 'uv run --project /code manage.py shell'

[build]

[env]
  PORT = '8000'
  AWS_ROLE_ARN = "arn:aws:iam::984616268605:role/fly-io-fuckyour-email"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
